/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "VuePress Blog Example",
  "description": "This is a blog example built by VuePress",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "alternate",
        "type": "application/rss+xml",
        "href": "https://example.vuepress-theme-blog.ulivz.com/rss.xml",
        "title": "VuePress Blog Example RSS Feed"
      }
    ]
  ],
  "pages": [
    {
      "title": "frontmatter in vuepress 2",
      "frontmatter": {
        "title": "frontmatter in vuepress 2",
        "date": "2018-11-7",
        "tags": [
          "frontmatter",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "description": "\nAny markdown file that contains a YAML front matter block will be processed by gray-matter. The front matter must be the first thing in the markdown ...",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2018-11-7-frontmatter-in-vuepress-2.html",
      "relativePath": "_posts/2018-11-7-frontmatter-in-vuepress-2.md",
      "key": "v-74d237c0",
      "path": "/2018/11/07/frontmatter-in-vuepress-2/",
      "headers": [
        {
          "level": 2,
          "title": "Alternative Front Matter Formats",
          "slug": "alternative-front-matter-formats"
        },
        {
          "level": 2,
          "title": "Predefined Variables",
          "slug": "predefined-variables"
        },
        {
          "level": 3,
          "title": "title",
          "slug": "title"
        },
        {
          "level": 3,
          "title": "lang",
          "slug": "lang"
        },
        {
          "level": 3,
          "title": "description",
          "slug": "description"
        },
        {
          "level": 3,
          "title": "layout",
          "slug": "layout"
        },
        {
          "level": 3,
          "title": "permalink",
          "slug": "permalink"
        },
        {
          "level": 3,
          "title": "metaTitle",
          "slug": "metatitle"
        },
        {
          "level": 3,
          "title": "meta",
          "slug": "meta"
        },
        {
          "level": 2,
          "title": "Predefined Variables Powered By Default Theme",
          "slug": "predefined-variables-powered-by-default-theme"
        },
        {
          "level": 3,
          "title": "navbar",
          "slug": "navbar"
        },
        {
          "level": 3,
          "title": "sidebar",
          "slug": "sidebar"
        }
      ],
      "summary": "\nAny markdown file that contains a YAML front matter block will be processed by gray-matter. The front matter must be the first thing in the markdown ...",
      "id": "post",
      "pid": "post",
      "lastUpdated": "11/10/2020, 11:41:20 PM"
    },
    {
      "title": "frontmatter in vuepress 3",
      "frontmatter": {
        "title": "frontmatter in vuepress 3",
        "date": "2018-11-7",
        "tags": [
          "frontmatter",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "description": "Any markdown file that contains a YAML front matter block will be processed by gray-matter. The front matter must be the first thing in the markdown fil ...",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2018-11-7-frontmatter-in-vuepress-3.html",
      "relativePath": "_posts/2018-11-7-frontmatter-in-vuepress-3.md",
      "key": "v-b740aa84",
      "path": "/2018/11/07/frontmatter-in-vuepress-3/",
      "headers": [
        {
          "level": 2,
          "title": "Alternative Front Matter Formats",
          "slug": "alternative-front-matter-formats"
        },
        {
          "level": 2,
          "title": "Predefined Variables",
          "slug": "predefined-variables"
        },
        {
          "level": 3,
          "title": "title",
          "slug": "title"
        },
        {
          "level": 3,
          "title": "lang",
          "slug": "lang"
        },
        {
          "level": 3,
          "title": "description",
          "slug": "description"
        },
        {
          "level": 3,
          "title": "layout",
          "slug": "layout"
        },
        {
          "level": 3,
          "title": "permalink",
          "slug": "permalink"
        },
        {
          "level": 3,
          "title": "metaTitle",
          "slug": "metatitle"
        },
        {
          "level": 3,
          "title": "meta",
          "slug": "meta"
        },
        {
          "level": 2,
          "title": "Predefined Variables Powered By Default Theme",
          "slug": "predefined-variables-powered-by-default-theme"
        },
        {
          "level": 3,
          "title": "navbar",
          "slug": "navbar"
        },
        {
          "level": 3,
          "title": "sidebar",
          "slug": "sidebar"
        }
      ],
      "summary": "Any markdown file that contains a YAML front matter block will be processed by gray-matter. The front matter must be the first thing in the markdown fil ...",
      "id": "post",
      "pid": "post",
      "lastUpdated": "1/21/2020, 11:45:02 PM"
    },
    {
      "title": "frontmatter in vuepress 1",
      "frontmatter": {
        "title": "frontmatter in vuepress 1",
        "date": "2018-11-7",
        "tags": [
          "frontmatter",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "description": "Any markdown file that contains a YAML front matter block will be processed by gray-matter. The front matter must be the first thing in the markdown fil ...",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2018-11-7-frontmatter-in-vuepress.html",
      "relativePath": "_posts/2018-11-7-frontmatter-in-vuepress.md",
      "key": "v-414bfa0a",
      "path": "/2018/11/07/frontmatter-in-vuepress/",
      "headers": [
        {
          "level": 2,
          "title": "Alternative Front Matter Formats",
          "slug": "alternative-front-matter-formats"
        },
        {
          "level": 2,
          "title": "Predefined Variables",
          "slug": "predefined-variables"
        },
        {
          "level": 3,
          "title": "title",
          "slug": "title"
        },
        {
          "level": 3,
          "title": "lang",
          "slug": "lang"
        },
        {
          "level": 3,
          "title": "description",
          "slug": "description"
        },
        {
          "level": 3,
          "title": "layout",
          "slug": "layout"
        },
        {
          "level": 3,
          "title": "permalink",
          "slug": "permalink"
        },
        {
          "level": 3,
          "title": "metaTitle",
          "slug": "metatitle"
        },
        {
          "level": 3,
          "title": "meta",
          "slug": "meta"
        },
        {
          "level": 2,
          "title": "Predefined Variables Powered By Default Theme",
          "slug": "predefined-variables-powered-by-default-theme"
        },
        {
          "level": 3,
          "title": "navbar",
          "slug": "navbar"
        },
        {
          "level": 3,
          "title": "sidebar",
          "slug": "sidebar"
        }
      ],
      "excerpt": "<p>Any markdown file that contains a YAML front matter block will be processed by <a href=\"https://github.com/jonschlinkert/gray-matter\" target=\"_blank\" rel=\"noopener noreferrer\">gray-matter<OutboundLink/></a>. The front matter must be the first thing in the markdown file and must take the form of valid YAML set between triple-dashed lines. Here is a basic example:</p>\n",
      "summary": "Any markdown file that contains a YAML front matter block will be processed by gray-matter. The front matter must be the first thing in the markdown fil ...",
      "id": "post",
      "pid": "post",
      "lastUpdated": "6/9/2020, 8:05:11 PM"
    },
    {
      "title": "Markdown Slot 2",
      "frontmatter": {
        "title": "Markdown Slot 2",
        "date": "2019-2-26",
        "tags": [
          "markdown",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "description": "VuePress implements a content distribution API for Markdown. With this feature, you can split your document into multiple fragments to facilitate flexible composition in the layout component.\nWh ...",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2019-2-26-markdown-slot-2.html",
      "relativePath": "_posts/2019-2-26-markdown-slot-2.md",
      "key": "v-c84202b8",
      "path": "/2019/02/26/markdown-slot-2/",
      "headers": [
        {
          "level": 2,
          "title": "Why do I need Markdown Slot?",
          "slug": "why-do-i-need-markdown-slot"
        },
        {
          "level": 2,
          "title": "Named Slots",
          "slug": "named-slots"
        },
        {
          "level": 2,
          "title": "Default Slot Content",
          "slug": "default-slot-content"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ],
      "summary": "VuePress implements a content distribution API for Markdown. With this feature, you can split your document into multiple fragments to facilitate flexible composition in the layout component.\nWh ...",
      "id": "post",
      "pid": "post",
      "lastUpdated": "1/21/2020, 11:45:02 PM"
    },
    {
      "title": "Markdown Slot 3",
      "frontmatter": {
        "title": "Markdown Slot 3",
        "date": "2019-2-26",
        "tags": [
          "markdown",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "description": "VuePress implements a content distribution API for Markdown. With this feature, you can split your document into multiple fragments to facilitate flexible composition in the layout component.\nWh ...",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2019-2-26-markdown-slot-3.html",
      "relativePath": "_posts/2019-2-26-markdown-slot-3.md",
      "key": "v-b60de73c",
      "path": "/2019/02/26/markdown-slot-3/",
      "headers": [
        {
          "level": 2,
          "title": "Why do I need Markdown Slot?",
          "slug": "why-do-i-need-markdown-slot"
        },
        {
          "level": 2,
          "title": "Named Slots",
          "slug": "named-slots"
        },
        {
          "level": 2,
          "title": "Default Slot Content",
          "slug": "default-slot-content"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ],
      "summary": "VuePress implements a content distribution API for Markdown. With this feature, you can split your document into multiple fragments to facilitate flexible composition in the layout component.\nWh ...",
      "id": "post",
      "pid": "post",
      "lastUpdated": "1/21/2020, 11:45:02 PM"
    },
    {
      "title": "Markdown Slot 4",
      "frontmatter": {
        "title": "Markdown Slot 4",
        "date": "2019-2-26",
        "tags": [
          "markdown",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "description": "VuePress implements a content distribution API for Markdown. With this feature, you can split your document into multiple fragments to facilitate flexible composition in the layout component.\nWh ...",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2019-2-26-markdown-slot-4.html",
      "relativePath": "_posts/2019-2-26-markdown-slot-4.md",
      "key": "v-a3d9cbc0",
      "path": "/2019/02/26/markdown-slot-4/",
      "headers": [
        {
          "level": 2,
          "title": "Why do I need Markdown Slot?",
          "slug": "why-do-i-need-markdown-slot"
        },
        {
          "level": 2,
          "title": "Named Slots",
          "slug": "named-slots"
        },
        {
          "level": 2,
          "title": "Default Slot Content",
          "slug": "default-slot-content"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ],
      "summary": "VuePress implements a content distribution API for Markdown. With this feature, you can split your document into multiple fragments to facilitate flexible composition in the layout component.\nWh ...",
      "id": "post",
      "pid": "post",
      "lastUpdated": "1/21/2020, 11:45:02 PM"
    },
    {
      "title": "Markdown Slot 1",
      "frontmatter": {
        "title": "Markdown Slot 1",
        "date": "2019-2-26",
        "tags": [
          "markdown",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "description": "VuePress implements a content distribution API for Markdown. With this feature, you can split your document into multiple fragments to facilitate flexible composition in the layout component.\n<!-- ...",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2019-2-26-markdown-slot.html",
      "relativePath": "_posts/2019-2-26-markdown-slot.md",
      "key": "v-7d8e4ea4",
      "path": "/2019/02/26/markdown-slot/",
      "headers": [
        {
          "level": 2,
          "title": "Why do I need Markdown Slot?",
          "slug": "why-do-i-need-markdown-slot"
        },
        {
          "level": 2,
          "title": "Named Slots",
          "slug": "named-slots"
        },
        {
          "level": 2,
          "title": "Default Slot Content",
          "slug": "default-slot-content"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ],
      "excerpt": "<p>VuePress implements a content distribution API for Markdown. With this feature, you can split your document into multiple fragments to facilitate flexible composition in the layout component.</p>\n",
      "summary": "VuePress implements a content distribution API for Markdown. With this feature, you can split your document into multiple fragments to facilitate flexible composition in the layout component.\n<!-- ...",
      "id": "post",
      "pid": "post",
      "lastUpdated": "6/9/2020, 8:05:11 PM"
    },
    {
      "title": "writing a vuepress theme 2",
      "frontmatter": {
        "title": "writing a vuepress theme 2",
        "date": "2019-5-6",
        "tags": [
          "theme",
          "blog",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Shanghai",
        "description": "To write a theme, create a .vuepress/theme directory in your docs root, and then create a Layout.vue file:\n`\n.\n└─ .vuepress\n   └─ theme\n       └─ Layout.vue\n`\nFrom there it's the ...",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2019-5-6-writing-a-vuepress-theme-2.html",
      "relativePath": "_posts/2019-5-6-writing-a-vuepress-theme-2.md",
      "key": "v-35197614",
      "path": "/2019/05/06/writing-a-vuepress-theme-2/",
      "headers": [
        {
          "level": 2,
          "title": "Content Outlet",
          "slug": "content-outlet"
        },
        {
          "level": 2,
          "title": "Directory Structure",
          "slug": "directory-structure"
        },
        {
          "level": 2,
          "title": "Layout Component",
          "slug": "layout-component"
        },
        {
          "level": 2,
          "title": "Apply plugins",
          "slug": "apply-plugins"
        },
        {
          "level": 2,
          "title": "Site and Page Metadata",
          "slug": "site-and-page-metadata"
        },
        {
          "level": 2,
          "title": "App Level Enhancements",
          "slug": "app-level-enhancements"
        }
      ],
      "summary": "To write a theme, create a .vuepress/theme directory in your docs root, and then create a Layout.vue file:\n`\n.\n└─ .vuepress\n   └─ theme\n       └─ Layout.vue\n`\nFrom there it's the ...",
      "id": "post",
      "pid": "post",
      "lastUpdated": "6/9/2020, 8:05:11 PM"
    },
    {
      "title": "writing a vuepress theme 3",
      "frontmatter": {
        "title": "writing a vuepress theme 3",
        "date": "2019-5-6",
        "tags": [
          "theme",
          "blog",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Shanghai",
        "description": "To write a theme, create a .vuepress/theme directory in your docs root, and then create a Layout.vue file:\n`\n.\n└─ .vuepress\n   └─ theme\n       └─ Layout.vue\n`\nFrom there it's the ...",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2019-5-6-writing-a-vuepress-theme-3.html",
      "relativePath": "_posts/2019-5-6-writing-a-vuepress-theme-3.md",
      "key": "v-1500b7f4",
      "path": "/2019/05/06/writing-a-vuepress-theme-3/",
      "headers": [
        {
          "level": 2,
          "title": "Content Outlet",
          "slug": "content-outlet"
        },
        {
          "level": 2,
          "title": "Directory Structure",
          "slug": "directory-structure"
        },
        {
          "level": 2,
          "title": "Layout Component",
          "slug": "layout-component"
        },
        {
          "level": 2,
          "title": "Apply plugins",
          "slug": "apply-plugins"
        },
        {
          "level": 2,
          "title": "Site and Page Metadata",
          "slug": "site-and-page-metadata"
        },
        {
          "level": 2,
          "title": "App Level Enhancements",
          "slug": "app-level-enhancements"
        }
      ],
      "summary": "To write a theme, create a .vuepress/theme directory in your docs root, and then create a Layout.vue file:\n`\n.\n└─ .vuepress\n   └─ theme\n       └─ Layout.vue\n`\nFrom there it's the ...",
      "id": "post",
      "pid": "post",
      "lastUpdated": "6/9/2020, 8:05:11 PM"
    },
    {
      "title": "writing a vuepress theme 4",
      "frontmatter": {
        "title": "writing a vuepress theme 4",
        "date": "2019-5-6",
        "tags": [
          "theme",
          "blog",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Shanghai",
        "description": "To write a theme, create a .vuepress/theme directory in your docs root, and then create a Layout.vue file:\n`\n.\n└─ .vuepress\n   └─ theme\n       └─ Layout.vue\n`\nFrom there it's the ...",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2019-5-6-writing-a-vuepress-theme-4.html",
      "relativePath": "_posts/2019-5-6-writing-a-vuepress-theme-4.md",
      "key": "v-448e2af2",
      "path": "/2019/05/06/writing-a-vuepress-theme-4/",
      "headers": [
        {
          "level": 2,
          "title": "Content Outlet",
          "slug": "content-outlet"
        },
        {
          "level": 2,
          "title": "Directory Structure",
          "slug": "directory-structure"
        },
        {
          "level": 2,
          "title": "Layout Component",
          "slug": "layout-component"
        },
        {
          "level": 2,
          "title": "Apply plugins",
          "slug": "apply-plugins"
        },
        {
          "level": 2,
          "title": "Site and Page Metadata",
          "slug": "site-and-page-metadata"
        },
        {
          "level": 2,
          "title": "App Level Enhancements",
          "slug": "app-level-enhancements"
        }
      ],
      "summary": "To write a theme, create a .vuepress/theme directory in your docs root, and then create a Layout.vue file:\n`\n.\n└─ .vuepress\n   └─ theme\n       └─ Layout.vue\n`\nFrom there it's the ...",
      "id": "post",
      "pid": "post",
      "lastUpdated": "6/9/2020, 8:05:11 PM"
    },
    {
      "title": "Writing a vuepress theme 1",
      "frontmatter": {
        "title": "Writing a vuepress theme 1",
        "date": "2019-5-6",
        "tags": [
          "theme",
          "blog",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Shanghai",
        "description": "To write a theme, create a .vuepress/theme directory in your docs root, and then create a Layout.vue file:\n`\n.\n└─ .vuepress\n   └─ theme\n       └─ Layout.vue\n`\nFrom there it's the ...",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/_posts/2019-5-6-writing-a-vuepress-theme.html",
      "relativePath": "_posts/2019-5-6-writing-a-vuepress-theme.md",
      "key": "v-73bbe100",
      "path": "/2019/05/06/writing-a-vuepress-theme/",
      "headers": [
        {
          "level": 2,
          "title": "Content Outlet",
          "slug": "content-outlet"
        },
        {
          "level": 2,
          "title": "Directory Structure",
          "slug": "directory-structure"
        },
        {
          "level": 2,
          "title": "Layout Component",
          "slug": "layout-component"
        },
        {
          "level": 2,
          "title": "Apply plugins",
          "slug": "apply-plugins"
        },
        {
          "level": 2,
          "title": "Site and Page Metadata",
          "slug": "site-and-page-metadata"
        },
        {
          "level": 2,
          "title": "App Level Enhancements",
          "slug": "app-level-enhancements"
        }
      ],
      "excerpt": "<p>To write a theme, create a <code>.vuepress/theme</code> directory in your docs root, and then create a <code>Layout.vue</code> file:</p>\n<!--beforebegin--><div class=\"language- extra-class\"><!--afterbegin--><pre v-pre class=\"language-text\"><code>.\n└─ .vuepress\n   └─ `theme`\n       └─ Layout.vue\n</code></pre>\n<!--beforeend--></div><!--afterend--><p>From there it's the same as developing a normal Vue application. It is entirely up to you how to organize your theme.</p>\n",
      "summary": "To write a theme, create a .vuepress/theme directory in your docs root, and then create a Layout.vue file:\n`\n.\n└─ .vuepress\n   └─ theme\n       └─ Layout.vue\n`\nFrom there it's the ...",
      "id": "post",
      "pid": "post",
      "lastUpdated": "6/9/2020, 8:05:11 PM"
    },
    {
      "title": "About Me",
      "frontmatter": {
        "description": " ..."
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-0fa2af29",
      "path": "/about.html",
      "summary": " ...",
      "lastUpdated": "6/23/2019, 5:52:54 PM"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Post"
      },
      "regularPath": "/",
      "key": "v-b2754d56",
      "path": "/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Tag"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "frontmatter Tag"
      },
      "regularPath": "/tag/frontmatter/",
      "key": "v-f8241222",
      "path": "/tag/frontmatter/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "vuepress Tag"
      },
      "regularPath": "/tag/vuepress/",
      "key": "v-dfb71430",
      "path": "/tag/vuepress/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "markdown Tag"
      },
      "regularPath": "/tag/markdown/",
      "key": "v-3ae5b494",
      "path": "/tag/markdown/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "theme Tag"
      },
      "regularPath": "/tag/theme/",
      "key": "v-58f012a0",
      "path": "/tag/theme/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "blog Tag"
      },
      "regularPath": "/tag/blog/",
      "key": "v-1559f73a",
      "path": "/tag/blog/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 | Post"
      },
      "regularPath": "/page/2/",
      "key": "v-8fdafa70",
      "path": "/page/2/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 3 | Post"
      },
      "regularPath": "/page/3/",
      "key": "v-8fdafa32",
      "path": "/page/3/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 - vuepress | Tag"
      },
      "regularPath": "/tag/vuepress/page/2/",
      "key": "v-c5eeaa56",
      "path": "/tag/vuepress/page/2/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 3 - vuepress | Tag"
      },
      "regularPath": "/tag/vuepress/page/3/",
      "key": "v-c5eeaa18",
      "path": "/tag/vuepress/page/3/"
    }
  ],
  "themeConfig": {
    "footer": {
      "contact": [
        {
          "type": "codepen",
          "link": "/"
        },
        {
          "type": "codesandbox",
          "link": "/"
        },
        {
          "type": "facebook",
          "link": "/"
        },
        {
          "type": "github",
          "link": "https://github.com/vuepressjs/vuepress-theme-blog"
        },
        {
          "type": "gitlab",
          "link": "/"
        },
        {
          "type": "instagram",
          "link": "/"
        },
        {
          "type": "linkedin",
          "link": "/"
        },
        {
          "type": "mail",
          "link": "/"
        },
        {
          "type": "messenger",
          "link": "/"
        },
        {
          "type": "music",
          "link": "/"
        },
        {
          "type": "phone",
          "link": "/"
        },
        {
          "type": "twitter",
          "link": "https://twitter.com/vuepressjs"
        },
        {
          "type": "video",
          "link": "/"
        },
        {
          "type": "web",
          "link": "/"
        },
        {
          "type": "youtube",
          "link": "/"
        }
      ],
      "copyright": [
        {
          "text": "Privacy Policy",
          "link": "https://policies.google.com/privacy?hl=en-US"
        },
        {
          "text": "MIT Licensed | Copyright © 2018-present Vue.js"
        }
      ]
    },
    "sitemap": {
      "hostname": "https://example.vuepress-theme-blog.ulivz.com/"
    },
    "comment": {
      "service": "disqus",
      "shortname": "vuepress-plugin-blog"
    },
    "newsletter": {
      "endpoint": "https://billyyyyy3320.us4.list-manage.com/subscribe/post?u=4905113ee00d8210c2004e038&amp;id=bd18d40138"
    },
    "feed": {
      "canonical_base": "https://example.vuepress-theme-blog.ulivz.com/"
    },
    "smoothScroll": true,
    "nav": [
      {
        "text": "Blog",
        "link": "/"
      },
      {
        "text": "Tags",
        "link": "/tag/"
      }
    ],
    "summary": true,
    "summaryLength": 200,
    "pwa": false
  }
}