/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tag": {
    "frontmatter": {
      "key": "frontmatter",
      "scope": "tag",
      "path": "/tag/frontmatter/",
      "pageKeys": [
        "v-74d237c0",
        "v-b740aa84",
        "v-414bfa0a"
      ]
    },
    "vuepress": {
      "key": "vuepress",
      "scope": "tag",
      "path": "/tag/vuepress/",
      "pageKeys": [
        "v-74d237c0",
        "v-b740aa84",
        "v-414bfa0a",
        "v-c84202b8",
        "v-b60de73c",
        "v-a3d9cbc0",
        "v-7d8e4ea4",
        "v-35197614",
        "v-1500b7f4",
        "v-448e2af2",
        "v-73bbe100"
      ]
    },
    "markdown": {
      "key": "markdown",
      "scope": "tag",
      "path": "/tag/markdown/",
      "pageKeys": [
        "v-c84202b8",
        "v-b60de73c",
        "v-a3d9cbc0",
        "v-7d8e4ea4"
      ]
    },
    "theme": {
      "key": "theme",
      "scope": "tag",
      "path": "/tag/theme/",
      "pageKeys": [
        "v-35197614",
        "v-1500b7f4",
        "v-448e2af2",
        "v-73bbe100"
      ]
    },
    "blog": {
      "key": "blog",
      "scope": "tag",
      "path": "/tag/blog/",
      "pageKeys": [
        "v-35197614",
        "v-1500b7f4",
        "v-448e2af2",
        "v-73bbe100"
      ]
    }
  }
}