-- Script generated by GameGuardian 101.0 (16139) at 2021-01-28 10:24:25 for Higgs Domino [com.neptune.domino 1.64 (1641)]
-- Lua help: http://gameguardian.net/help/

-- options
local scriptName = [=====[Script for Higgs Domino 1.64]=====]
local scriptVersion = '1.0.0'
local scriptAuthor = 'User'
local startToast = ''
-- 0 - no check; 1 - check package only, 2 - check package and build
local checkTarget = 0

local targetName = [=====[Higgs Domino]=====]
local targetPkg = 'com.neptune.domino'
local targetVersion = [=====[1.64]=====]
local targetBuild = 1641

-- functions

-- init
gg.require('101.0', 16139)

if startToast ~= '' then startToast = '\n'..startToast end
gg.toast(scriptName..' v'..scriptVersion..' by '..scriptAuthor..startToast)

if checkTarget ~= 0 then
	local info = gg.getTargetInfo()
	local check = false
	local current = false
	if checkTarget >= 1 then
		check = targetPkg
		current = info.packageName
	end
	if checkTarget >= 2 then
		check = check..' '..targetVersion..' ('..targetBuild..')'
		current = current..' '..info.versionName..' ('..info.versionCode..')'
	end
	if check ~= current then
		gg.alert('This script for "'..targetName..'" ['..check..'].\nYou select "'..info.label..'" ['..current..'].\nNow script exit.')
		os.exit()
	end
end
local revert = nil

-- main code

gg.clearResults()
gg.searchNumber("1800000", gg.TYPE_AUTO, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.processResume()
gg.timeJump("1:1:0")
gg.searchFuzzy("0", gg.SIGN_FUZZY_EQUAL, gg.TYPE_DWORD | gg.TYPE_XOR | gg.TYPE_FLOAT | gg.TYPE_QWORD | gg.TYPE_DOUBLE, 0, -1, 0)
revert = gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll("176000000", gg.TYPE_DWORD)
revert = gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll("176000000", gg.TYPE_QWORD)
