-- Script generated by GameGuardian 101.0 (16139) at 2021-02-01 02:24:07 for Domino [com.higgs.domino 1.64 (164)]
-- Lua help: http://gameguardian.net/help/

-- options
local scriptName = [=====[Script for Domino 1.64]=====]
local scriptVersion = '1.0.0'
local scriptAuthor = 'User'
local startToast = ''
-- 0 - no check; 1 - check package only, 2 - check package and build
local checkTarget = 0

local targetName = [=====[Domino]=====]
local targetPkg = 'com.higgs.domino'
local targetVersion = [=====[1.64]=====]
local targetBuild = 164

-- functions

-- init
gg.require('101.0', 16139)

if startToast ~= '' then startToast = '\n'..startToast end
gg.toast(scriptName..' v'..scriptVersion..' by '..scriptAuthor..startToast)

if checkTarget ~= 0 then
	local info = gg.getTargetInfo()
	local check = false
	local current = false
	if checkTarget >= 1 then
		check = targetPkg
		current = info.packageName
	end
	if checkTarget >= 2 then
		check = check..' '..targetVersion..' ('..targetBuild..')'
		current = current..' '..info.versionName..' ('..info.versionCode..')'
	end
	if check ~= current then
		gg.alert('This script for "'..targetName..'" ['..check..'].\nYou select "'..info.label..'" ['..current..'].\nNow script exit.')
		os.exit()
	end
end
local revert = nil

-- main code

gg.toast('bet 6.8k')
gg.searchNumber("6800000", gg.TYPE_AUTO, false, gg.SIGN_EQUAL, 0, -1, 0)
revert = gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll("176000000", gg.TYPE_DWORD)
gg.refineNumber("6800000", gg.TYPE_AUTO, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.searchNumber("17000000", gg.TYPE_AUTO, false, gg.SIGN_EQUAL, 0, -1, 0)
revert = gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll("440000000", gg.TYPE_DWORD)
gg.refineNumber("17000000", gg.TYPE_AUTO, false, gg.SIGN_EQUAL, 0, -1, 0)
gg.searchNumber("34000000", gg.TYPE_AUTO, false, gg.SIGN_EQUAL, 0, -1, 0)
revert = gg.getResults(100, nil, nil, nil, nil, nil, nil, nil, nil)
gg.editAll("880000000", gg.TYPE_DWORD)
gg.refineNumber("34000000", gg.TYPE_AUTO, false, gg.SIGN_EQUAL, 0, -1, 0)
