/**
 * Generated by "vuepress-plugin-mailchimp"
 */

    const { endpoint, submitText, content, title, popupConfig = {} } = {"endpoint":"https://billyyyyy3320.us4.list-manage.com/subscribe/post?u=4905113ee00d8210c2004e038&amp;id=bd18d40138"}
    
    const {
    enabled: popupEnabled = true,
    component: popupComponent = "Popup",
    timeout: popupTimeout = 3000
    } = popupConfig;
    
    export { endpoint, submitText, content, title, popupEnabled, popupComponent, popupTimeout };