exports.modules = [
  './js/_intro-mdb-pro.js',
  './js/vendor/free/jquery.easing.js',
  './js/vendor/free/velocity.js',
  './js/vendor/free/chart.js',
  './js/vendor/free/chartjs-datalabels.js',
  './js/dist/free/wow.js',
  './js/dist/free/scrolling-navbar.js',
  './js/vendor/free/waves.js',
  './js/dist/free/forms-free.js',
  './js/dist/pro/preloading.js',
  './js/dist/pro/cards.js',
  './js/dist/pro/character-counter.js',
  './js/vendor/pro/toastr.js',
  './js/dist/pro/smooth-scroll.js',
  './js/dist/pro/buttons.js',
  './js/dist/pro/sidenav.js',
  './js/dist/pro/collapsible.js',
  './js/dist/pro/range-input.js',
  './js/dist/pro/file-input.js',
  './js/dist/pro/dropdown/dropdown.js',
  './js/dist/pro/dropdown/dropdown-searchable.js',
  './js/dist/pro/material-select/material-select-view-renderer.js',
  './js/dist/pro/material-select/material-select-view.js',
  './js/dist/pro/material-select/material-select.js',
  './js/vendor/pro/picker.js',
  './js/vendor/pro/picker-date.js',
  './js/vendor/pro/picker-time.js',
  './js/vendor/pro/picker-date-time.js',
  './js/vendor/pro/lightbox.js',
  './js/vendor/pro/scrollbar.js',
  './js/dist/pro/chips.js',
  './js/vendor/pro/ofi.js',
  './js/vendor/pro/jarallax.js',
  './js/vendor/pro/jarallax-video.js',
  './js/dist/pro/mdb-autocomplete.js',
  './js/vendor/free/enhanced-modals.js',
  './js/dist/free/treeview.js',
  './js/vendor/free/bs-custom-file-input.js',
  './js/dist/pro/sticky.js'
  // './js/vendor/addons/jquery.zmd.hierarchical-display.js/',
  // './js/vendor/addons/masonry.pkgd.min.js',
  // './js/vendor/addons/imagesloaded.pkgd.min.js',
  // './js/vendor/addons/datatables.js',
  // './js/vendor/addons/rating.js',
  // './js/vendor/addons/progressBar.js',
  // './js/vendor/addons-pro/timeline.js',
  // './js/vendor/addons-pro/steppers.js',
  // './js/vendor/addons-pro/multi-range.js',
  // './js/vendor/addons-pro/chat.js',
  // './js/vendor/addons-pro/simple-charts.js'
];

