# Header
menu:
  home: /
  archive: /archives

# Content
lightbox: true

# Miscellaneous
google_analytics: 

# Article schema
# https://developers.google.com/structured-data/rich-snippets/articles#article_markup_properties
schema:
  image:
    url: /img/700.png
    height: 700 
    width: 700 # <= 696
  publisher:
    name: Yourpublisher
    logo:
      url: /img/700.png
      width: 600 # <= 600
      height: 60 # >= 60
