# dont transform to amp style
amp: false
# disqus comment shortname
disqus_shortname: dimaslanjaka

# nav links to include in navigation bar
nav:
- url: /page/about-me.html
  title: About Me
- url: /p/search.html
  title: Search Engine

# featured posts to include in footer
featured:
- url: "https://www.webmanajemen.com/The%20Legend%20Of%20Neverland/Quiz.html"
  title: Quiz The Legend Of Neverland
  excerpt: Scenic Quiz Answer The Legend Of Neverland
  img: "https://www.webmanajemen.com/The%20Legend%20Of%20Neverland/Quiz/SCENIC-QUIZ.jpg"
- url: "http://www.webmanajemen.com/2017/04/instal-php-cli-pada-android-instalasi.html"
  title: Install PHP CLI for android
  excerpt: How to install php cli on android rooted
  img: "https://4.bp.blogspot.com/-3UATHL878wU/WKoXE11tarI/AAAAAAAAFAA/QhBnNJFo5QAiB4C04RKBG9zuFrP2Uhm4gCLcB/s1600/serverphp.jpg"
- url: "https://www.webmanajemen.com/Chimeraland/Pets.html"
  excerpt: Chimeraland Pets Information
  title: Chimeraland Pets Information
  img: "https://www.webmanajemen.com/Chimeraland/Pets/cover.jpg"