# Header
menu:
  home: /
  archive: /archives

# Content
lightbox: true

# Miscellaneous
google_analytics: G-BG75CLNJZ1

adsense:
  pub: ca-pub-1165447249910969

# Article schema
# https://developers.google.com/structured-data/rich-snippets/articles#article_markup_properties
schema:
  image:
    url: /img/700.png
    height: 700
    width: 700 # <= 696
  publisher:
    name: Dimas Lanjaka
    logo:
      url: /img/700.png
      width: 600 # <= 600
      height: 60 # >= 60
