name: Build With Multiple NodeJS Versions

on:
  # schedule this job every 1:45 AM everydays
  schedule:
    - cron: '45 1 * * *'

#on:
  #pull_request:
    #branches:
      #- compiler # run when this branch pull requested
  #push:
    #branches:
      #- compiler # run when this branch pushed

# cancel previous workflows, run only one workflow
concurrency:
  group: multiversion-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-npm-package:
    #if: ${{ false }} # disable
    name: Test Build With NPM Packages
    #needs: build
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x]
    env:
      NODE_OPTIONS: "--max_old_space_size=8192" #8192
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - id: npm-install
        continue-on-error: true
        run: npm i -g npm hexo-cli gulp-cli typescript ts-node && npm ci
      - name: install additional dependencies
        id: npm-install-submodules
        continue-on-error: true
        #run: npm i git+https://github.com/dimaslanjaka/hexo-blogger-xml.git git+https://github.com/dimaslanjaka/hexo-seo.git git+https://github.com/dimaslanjaka/hexo-adsense.git
        run: npm i hexo-seo hexo-blogger-xml hexo-adsense

      #### ONLY RUN BELOW RUNNER IF ABOVE INSTALLATIONS SUCCEEDED ####
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: cd themes/material && npm install
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: npx gulp article:copy
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: hexo generate
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: cd docs/page && npm install
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        name: Userscripts
        run: |
          node userscripts/custom-domain.js
          node userscripts/copy.js
          node userscripts/after_generated.js
          node userscripts/validate.js

  test-git-package:
    #if: ${{ false }} # disable
    name: Test Build With GIT Packages
    #needs: test-npm-package
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x]
    env:
      NODE_OPTIONS: "--max_old_space_size=8192" #8192
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - id: npm-install
        continue-on-error: true
        run: npm i -g npm hexo-cli gulp-cli typescript ts-node && npm ci
      - name: install additional dependencies
        id: npm-install-submodules
        continue-on-error: true
        run: npm i git+https://github.com/dimaslanjaka/hexo-blogger-xml.git git+https://github.com/dimaslanjaka/hexo-seo.git git+https://github.com/dimaslanjaka/hexo-adsense.git
        #run: npm i hexo-seo hexo-blogger-xml hexo-adsense

      #### ONLY RUN BELOW RUNNER IF ABOVE INSTALLATIONS SUCCEEDED ####
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: cd themes/material && npm install
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: npx gulp article:copy
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: hexo generate
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: cd docs/page && npm install
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        name: Userscripts
        run: |
          node userscripts/custom-domain.js
          node userscripts/copy.js
          node userscripts/after_generated.js
          node userscripts/validate.js

